// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestoBackEnd.Data;

#nullable disable

namespace RestoBackEnd.Migrations
{
    [DbContext(typeof(RestoDbContext))]
    [Migration("20251221004357_AddKitchenOrderTable")]
    partial class AddKitchenOrderTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RestoBackEnd.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "أحمد",
                            Role = "Waiter"
                        },
                        new
                        {
                            Id = 2,
                            Name = "سارة",
                            Role = "Waiter"
                        },
                        new
                        {
                            Id = 3,
                            Name = "خالد",
                            Role = "Chef"
                        },
                        new
                        {
                            Id = 4,
                            Name = "ليلى",
                            Role = "Manager"
                        });
                });

            modelBuilder.Entity("RestoBackEnd.Models.KitchenOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChefName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("PreparationDuration")
                        .HasColumnType("int");

                    b.Property<DateTime>("PreparationStartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("KitchenOrders");
                });

            modelBuilder.Entity("RestoBackEnd.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OrderTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PaidAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TableId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalTax")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("RestoBackEnd.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("RestoBackEnd.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "main",
                            Description = "شاورما دجاج طازجة مع الخضار",
                            Name = "شاورما دجاج",
                            Price = 3.00m,
                            Quantity = 50
                        },
                        new
                        {
                            Id = 2,
                            Category = "main",
                            Description = "شاورما لحم بقري مع المخللات",
                            Name = "شاورما لحم",
                            Price = 4.00m,
                            Quantity = 40
                        },
                        new
                        {
                            Id = 3,
                            Category = "main",
                            Description = "برجر لحم مع الجبنة والخضار",
                            Name = "برجر لحم",
                            Price = 3.50m,
                            Quantity = 30
                        },
                        new
                        {
                            Id = 4,
                            Category = "appetizers",
                            Description = "بطاطا مقرمشة",
                            Name = "بطاطا مقلية",
                            Price = 1.50m,
                            Quantity = 100
                        },
                        new
                        {
                            Id = 5,
                            Category = "appetizers",
                            Description = "سلطة مع الجبنة الفيتا والزيتون",
                            Name = "سلطة يونانية",
                            Price = 2.00m,
                            Quantity = 20
                        },
                        new
                        {
                            Id = 6,
                            Category = "appetizers",
                            Description = "حمص طحينة مع زيت الزيتون",
                            Name = "حمص",
                            Price = 1.00m,
                            Quantity = 25
                        },
                        new
                        {
                            Id = 7,
                            Category = "drinks",
                            Description = "مشروب غازي 330 مل",
                            Name = "بيبسي",
                            Price = 0.50m,
                            Quantity = 200
                        },
                        new
                        {
                            Id = 8,
                            Category = "drinks",
                            Description = "عصير برتقال طازج",
                            Name = "عصير برتقال",
                            Price = 1.50m,
                            Quantity = 50
                        },
                        new
                        {
                            Id = 9,
                            Category = "drinks",
                            Description = "زجاجة ماء 500 مل",
                            Name = "ماء",
                            Price = 0.25m,
                            Quantity = 300
                        });
                });

            modelBuilder.Entity("RestoBackEnd.Models.Table", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<bool>("IsOccupied")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tables");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 4,
                            IsOccupied = false,
                            Name = "طاولة 1"
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 2,
                            IsOccupied = false,
                            Name = "طاولة 2"
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 6,
                            IsOccupied = false,
                            Name = "طاولة 3"
                        },
                        new
                        {
                            Id = 4,
                            Capacity = 4,
                            IsOccupied = false,
                            Name = "طاولة 4"
                        },
                        new
                        {
                            Id = 5,
                            Capacity = 4,
                            IsOccupied = false,
                            Name = "طاولة 5"
                        },
                        new
                        {
                            Id = 6,
                            Capacity = 8,
                            IsOccupied = false,
                            Name = "طاولة 6"
                        });
                });

            modelBuilder.Entity("RestoBackEnd.Models.KitchenOrder", b =>
                {
                    b.HasOne("RestoBackEnd.Models.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("RestoBackEnd.Models.OrderItem", b =>
                {
                    b.HasOne("RestoBackEnd.Models.Order", null)
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RestoBackEnd.Models.Order", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
